// 商品数据
const products = [
    {
        id: 1,
        name: '智能蓝牙耳机 Pro',
        category: '数码',
        price: 299,
        originalPrice: 499,
        emoji: '🎧',
        desc: '主动降噪，40小时续航，Hi-Fi音质',
        tag: '热卖',
    },
    {
        id: 2,
        name: '轻薄羽绒夹克',
        category: '服饰',
        price: 459,
        originalPrice: 899,
        emoji: '🧥',
        desc: '90%白鹅绒填充，防风防水面料',
        tag: '新品',
    },
    {
        id: 3,
        name: '有机绿茶礼盒装',
        category: '食品',
        price: 168,
        originalPrice: 258,
        emoji: '🍵',
        desc: '明前采摘，手工炒制，送礼佳品',
        tag: '',
    },
    {
        id: 4,
        name: '北欧风台灯',
        category: '家居',
        price: 189,
        originalPrice: 329,
        emoji: '💡',
        desc: '三档调光，护眼LED，极简设计',
        tag: '',
    },
    {
        id: 5,
        name: '运动跑步鞋',
        category: '服饰',
        price: 329,
        originalPrice: 599,
        emoji: '👟',
        desc: '超轻透气，缓震回弹，专业跑鞋',
        tag: '热卖',
    },
    {
        id: 6,
        name: '便携充电宝 20000mAh',
        category: '数码',
        price: 129,
        originalPrice: 199,
        emoji: '🔋',
        desc: '快充协议，数显电量，可带上飞机',
        tag: '',
    },
    {
        id: 7,
        name: '手工陶瓷花瓶',
        category: '家居',
        price: 89,
        originalPrice: 159,
        emoji: '🏺',
        desc: '高温烧制，哑光釉面，ins风摆件',
        tag: '新品',
    },
    {
        id: 8,
        name: '坚果大礼包',
        category: '食品',
        price: 99,
        originalPrice: 188,
        emoji: '🥜',
        desc: '6种坚果混装，每日一包营养均衡',
        tag: '',
    },
    {
        id: 9,
        name: '机械键盘 RGB',
        category: '数码',
        price: 249,
        originalPrice: 429,
        emoji: '⌨️',
        desc: 'Cherry轴体，全键热插拔，PBT键帽',
        tag: '',
    },
    {
        id: 10,
        name: '纯棉四件套',
        category: '家居',
        price: 259,
        originalPrice: 479,
        emoji: '🛏️',
        desc: '60支长绒棉，亲肤透气，多色可选',
        tag: '热卖',
    },
    {
        id: 11,
        name: '智能手表 S3',
        category: '数码',
        price: 599,
        originalPrice: 899,
        emoji: '⌚',
        desc: '血氧心率监测，14天续航，IP68防水',
        tag: '新品',
    },
    {
        id: 12,
        name: '手工牛皮钱包',
        category: '服饰',
        price: 199,
        originalPrice: 359,
        emoji: '👝',
        desc: '头层牛皮，手工缝制，复古做旧',
        tag: '',
    },
];

// 获取所有分类
function getCategories() {
    const cats = new Set(products.map(p => p.category));
    return ['all', ...Array.from(cats)];
}
