// 商品数据
const products = [
    // ====== 鞋子 ======
    {
        id: 1,
        name: 'Onitsuka Tiger MEXICO 66 亚瑟士鬼冢虎复古经典板鞋',
        category: '鞋子',
        price: 150,
        originalPrice: 399,
        image: 'images/product_1.jpg',
        desc: '高端品质工厂直发，复古经典款',
        tag: '热卖',
    },

    // ====== 裤子 ======
    {
        id: 2,
        name: '克罗心复古黑色牛仔短裤',
        category: '裤子',
        price: 69,
        originalPrice: 199,
        image: 'images/product_2.jpg',
        desc: '独家版本克罗心，十字架男士休闲中裤',
        tag: '热卖',
    },
    {
        id: 3,
        name: '美式高街牛仔短裤',
        category: '裤子',
        price: 59,
        originalPrice: 169,
        image: 'images/product_3.jpg',
        desc: '夏季宽松直筒中裤，松紧腰潮流短裤',
        tag: '新品',
    },
    {
        id: 4,
        name: '迪奥黑色刺绣牛仔裤',
        category: '裤子',
        price: 79,
        originalPrice: 229,
        image: 'images/product_4.jpg',
        desc: '高版本揭阳轻奢，黑色刺绣男款',
        tag: '热卖',
    },
    {
        id: 5,
        name: '福神浅蓝复古刺绣牛仔裤',
        category: '裤子',
        price: 79,
        originalPrice: 229,
        image: 'images/product_5.jpg',
        desc: '高版本揭阳轻奢，浅蓝复古刺绣男款',
        tag: '热卖',
    },
    {
        id: 6,
        name: '普拉达浅蓝三角标牛仔裤',
        category: '裤子',
        price: 79,
        originalPrice: 229,
        image: 'images/product_6.jpg',
        desc: '高版本揭阳轻奢，三角标牛仔裤男款',
        tag: '热卖',
    },
    {
        id: 11,
        name: '广州高版本潮牌牛仔裤',
        category: '裤子',
        price: 98,
        originalPrice: 269,
        image: 'images/product_7.jpg',
        desc: '广州高版本潮牌，百搭牛仔裤',
        tag: '新品',
    },
    {
        id: 15,
        name: '高品质普拉达直筒牛仔裤',
        category: '裤子',
        price: 48.80,
        originalPrice: 149,
        image: 'images/product_8.jpg',
        desc: '直筒修身百搭，揭阳现货现发',
        tag: '热卖',
    },
    {
        id: 16,
        name: '克罗心潮牌直筒牛仔短裤',
        category: '裤子',
        price: 58,
        originalPrice: 169,
        image: 'images/product_9.jpg',
        desc: '十字架拼接牛仔裤，潮牌直筒',
        tag: '热卖',
    },
    {
        id: 18,
        name: '战马刺绣休闲长裤',
        category: '裤子',
        price: 79,
        originalPrice: 229,
        image: 'images/product_10.jpg',
        desc: '网红刺绣高版本，直筒轻奢百搭修身抗皱',
        tag: '热卖',
    },
    {
        id: 19,
        name: '天丝醋酸轻奢休闲裤',
        category: '裤子',
        price: 128,
        originalPrice: 329,
        image: 'images/product_11.jpg',
        desc: '高版本新款，直筒薄款微宽松男裤',
        tag: '新品',
    },
    {
        id: 23,
        name: '克罗心十字架贴布蓝牛仔裤',
        category: '裤子',
        price: 89,
        originalPrice: 249,
        image: 'images/product_12.jpg',
        desc: '新款高版本轻奢，男女同款广州现货',
        tag: '新品',
    },
    {
        id: 25,
        name: '普拉达户外弯刀休闲长裤',
        category: '裤子',
        price: 88,
        originalPrice: 239,
        image: 'images/product_13.jpg',
        desc: '秋冬薄款三角休闲裤，男女速干宽松',
        tag: '新品',
    },
    {
        id: 26,
        name: '普拉达黑色直筒牛仔裤',
        category: '裤子',
        price: 78,
        originalPrice: 219,
        image: 'images/product_14.jpg',
        desc: '最新款轻奢高端潮牌，休闲修身直筒',
        tag: '热卖',
    },

    // ====== 外套 ======
    {
        id: 7,
        name: '潮牌轻奢牛仔外套',
        category: '外套',
        price: 228,
        originalPrice: 599,
        image: 'images/product_15.jpg',
        desc: '高版本潮牌轻奢上衣，独家款式',
        tag: '新品',
    },
    {
        id: 8,
        name: '连帽夹克外套',
        category: '外套',
        price: 99,
        originalPrice: 299,
        image: 'images/product_16.jpg',
        desc: '独家版本高质量高品质，百搭时尚男款',
        tag: '热卖',
    },
    {
        id: 9,
        name: 'Lvv拉链棒球开衫外套',
        category: '外套',
        price: 138.80,
        originalPrice: 369,
        image: 'images/product_17.jpg',
        desc: '新版顶级版本，万针刺绣外套',
        tag: '热卖',
    },
    {
        id: 17,
        name: '克罗心破洞毛衣',
        category: '外套',
        price: 89,
        originalPrice: 259,
        image: 'images/product_18.jpg',
        desc: '新款高版本，十字架皮标刺绣流苏破洞',
        tag: '新品',
    },
    {
        id: 24,
        name: '普拉达假两件针织衫',
        category: '外套',
        price: 129,
        originalPrice: 349,
        image: 'images/product_19.jpg',
        desc: '市面最高版本，毛衣羊毛衬衫拼接',
        tag: '热卖',
    },
    {
        id: 27,
        name: '满印连帽加棉外套',
        category: '外套',
        price: 179,
        originalPrice: 469,
        image: 'images/product_20.jpg',
        desc: '秋季轻奢新品，高品质现货独家首发',
        tag: '新品',
    },
    {
        id: 28,
        name: '普拉达高版本鹿皮外套',
        category: '外套',
        price: 279,
        originalPrice: 699,
        image: 'images/product_21.jpg',
        desc: '三标全齐，独家版本高品质',
        tag: '新品',
    },
    {
        id: 29,
        name: '大鹅排骨羽绒服',
        category: '外套',
        price: 269,
        originalPrice: 699,
        image: 'images/product_22.jpg',
        desc: '秋季轻奢新品，高品质现货独家首发',
        tag: '新品',
    },

    // ====== 卫衣 ======
    {
        id: 10,
        name: 'Lvv轻奢连帽卫衣',
        category: '卫衣',
        price: 129,
        originalPrice: 349,
        image: 'images/product_23.jpg',
        desc: '顶级版本轻奢系列，连帽外套卫衣',
        tag: '热卖',
    },

    // ====== 短袖 ======
    {
        id: 12,
        name: '字母logo刺绣圆领短袖T恤',
        category: '短袖',
        price: 79.90,
        originalPrice: 219,
        image: 'images/product_22.jpg',
        desc: '纯原1:1爆款高版本，百搭轻奢T恤',
        tag: '热卖',
    },
    {
        id: 13,
        name: '普拉达圆领刺绣短袖T恤',
        category: '短袖',
        price: 58,
        originalPrice: 169,
        image: 'images/product_21.jpg',
        desc: '高品质T恤，三标全齐',
        tag: '热卖',
    },
    {
        id: 14,
        name: '梅花刺绣Polo衫短袖',
        category: '短袖',
        price: 35.80,
        originalPrice: 119,
        image: 'images/product_20.jpg',
        desc: '新款百搭，修身短袖Polo衫',
        tag: '热卖',
    },
    {
        id: 20,
        name: '广州轻奢满印字母短袖T恤',
        category: '短袖',
        price: 99,
        originalPrice: 269,
        image: 'images/product_19.jpg',
        desc: '最高版本商务，男女同款',
        tag: '新品',
    },
    {
        id: 21,
        name: '普拉达立体剪裁短袖T恤',
        category: '短袖',
        price: 65,
        originalPrice: 189,
        image: 'images/product_18.jpg',
        desc: '新款纯棉超高版本，男女同款黑白两色',
        tag: '新品',
    },
    {
        id: 22,
        name: '普拉达Polo衫三角标短袖',
        category: '短袖',
        price: 55,
        originalPrice: 159,
        image: 'images/product_17.jpg',
        desc: '高版本轻奢潮牌，商务款男女短袖',
        tag: '新品',
    },
];

// 分类列表
const categoryList = ['all', '卫衣', '外套', '裤子', '鞋子', '帽子', '短袖'];

function getCategories() {
    return categoryList;
}
