// 商品数据
const products = [
    {
        id: 1,
        name: '智能蓝牙耳机 Pro',
        category: '数码',
        price: 299,
        originalPrice: 499,
        emoji: '🎧',
        desc: '主动降噪，40小时续航，高保真音质',
        tag: '热卖',
    },
    {
        id: 2,
        name: '轻薄羽绒夹克',
        category: '服饰',
        price: 459,
        originalPrice: 899,
        emoji: '🧥',
        desc: '90%白鹅绒填充，防风防水面料',
        tag: '新品',
    },
    {
        id: 3,
        name: '有机绿茶礼盒装',
        category: '食品',
        price: 168,
        originalPrice: 258,
        emoji: '🍵',
        desc: '明前采摘，手工炒制，送礼佳品',
        tag: '',
    },
    {
        id: 4,
        name: '北欧风台灯',
        category: '家居',
        price: 189,
        originalPrice: 329,
        emoji: '💡',
        desc: '三档调光，护眼LED光源，极简设计',
        tag: '',
    },
    {
        id: 5,
        name: '运动跑步鞋',
        category: '服饰',
        price: 329,
        originalPrice: 599,
        emoji: '👟',
        desc: '超轻透气，缓震回弹，专业跑鞋',
        tag: '热卖',
    },
    {
        id: 6,
        name: '便携充电宝 2万毫安',
        category: '数码',
        price: 129,
        originalPrice: 199,
        emoji: '🔋',
        desc: '快充协议，数显电量，可带上飞机',
        tag: '',
    },
    {
        id: 7,
        name: '手工陶瓷花瓶',
        category: '家居',
        price: 89,
        originalPrice: 159,
        emoji: '🏺',
        desc: '高温烧制，哑光釉面，网红风摆件',
        tag: '新品',
    },
    {
        id: 8,
        name: '坚果大礼包',
        category: '食品',
        price: 99,
        originalPrice: 188,
        emoji: '🥜',
        desc: '6种坚果混装，每日一包营养均衡',
        tag: '',
    },
    {
        id: 9,
        name: '机械键盘 炫彩背光',
        category: '数码',
        price: 249,
        originalPrice: 429,
        emoji: '⌨️',
        desc: '樱桃轴体，全键热插拔，PBT材质键帽',
        tag: '',
    },
    {
        id: 10,
        name: '纯棉四件套',
        category: '家居',
        price: 259,
        originalPrice: 479,
        emoji: '🛏️',
        desc: '60支长绒棉，亲肤透气，多色可选',
        tag: '热卖',
    },
    {
        id: 11,
        name: '智能手表 S3',
        category: '数码',
        price: 599,
        originalPrice: 899,
        emoji: '⌚',
        desc: '血氧心率监测，14天续航，IP68级防水',
        tag: '新品',
    },
    {
        id: 12,
        name: '手工牛皮钱包',
        category: '服饰',
        price: 199,
        originalPrice: 359,
        emoji: '👝',
        desc: '头层牛皮，手工缝制，复古做旧',
        tag: '',
    },
    {
        id: 13,
        name: '高版本轻奢克罗心牛仔裤（衣服）',
        category: '服饰',
        price: 79,
        originalPrice: 299,
        emoji: '👖',
        image: 'images/微信图片_20260627171551_42_2.jpg',
        desc: '十字架贴布印花，男女同款，广州现货秒发',
        tag: '新品',
    },
    {
        id: 14,
        name: '高版本轻奢克罗心牛仔裤（裤子）',
        category: '裤子',
        price: 79,
        originalPrice: 299,
        emoji: '👖',
        image: 'images/微信图片_20260627171552_43_2.jpg',
        desc: '十字架贴布印花，男女同款，广州现货秒发',
        tag: '新品',
    },
    {
        id: 15,
        name: '新款潮流T恤',
        category: '服饰',
        price: 89,
        originalPrice: 199,
        emoji: '👕',
        image: 'images/微信图片_20260627171552_44_2.jpg',
        desc: '纯棉面料，宽松版型，多色可选',
        tag: '新品',
    },
    {
        id: 16,
        name: '韩版宽松卫衣',
        category: '服饰',
        price: 109,
        originalPrice: 259,
        emoji: '🧥',
        image: 'images/微信图片_20260627171553_45_2.jpg',
        desc: '加绒保暖，街头潮流风，男女同款',
        tag: '',
    },
    {
        id: 17,
        name: '休闲运动裤',
        category: '裤子',
        price: 69,
        originalPrice: 159,
        emoji: '👖',
        image: 'images/微信图片_20260627171554_46_2.jpg',
        desc: '弹力面料，修身显瘦，运动休闲两穿',
        tag: '热卖',
    },
    {
        id: 18,
        name: '时尚连帽卫衣',
        category: '服饰',
        price: 119,
        originalPrice: 279,
        emoji: '🧥',
        image: 'images/微信图片_20260627171555_47_2.jpg',
        desc: '纯色简约，情侣款，秋冬必备',
        tag: '',
    },
    {
        id: 19,
        name: '夏季薄款短裤',
        category: '裤子',
        price: 59,
        originalPrice: 129,
        emoji: '🩳',
        image: 'images/微信图片_20260627171559_48_2.jpg',
        desc: '冰丝面料，透气速干，运动休闲',
        tag: '新品',
    },
    {
        id: 20,
        name: '潮流印花卫衣',
        category: '服饰',
        price: 129,
        originalPrice: 289,
        emoji: '👕',
        image: 'images/微信图片_20260627171602_49_2.jpg',
        desc: '3D数码印花，不掉色不缩水',
        tag: '热卖',
    },
    {
        id: 21,
        name: '工装束脚裤',
        category: '裤子',
        price: 85,
        originalPrice: 189,
        emoji: '👖',
        image: 'images/微信图片_20260627171604_50_2.jpg',
        desc: '多口袋设计，军工风，百搭神器',
        tag: '',
    },
];

// 获取所有分类
function getCategories() {
    const cats = new Set(products.map(p => p.category));
    return ['all', ...Array.from(cats)];
}
